### ISSUE TITLE
Update website (v2.3)

### ISSUE THREAD

**Issue by Gioser90** [OpenEmu/openemu.github.io#10]
**Before** | **After**
------------ | -------------
![org-step1](https://user-images.githubusercontent.com/16078125/105002622-df3ac480-5a31-11eb-8bea-d73ba1391d3c.jpg) | ![org-step1](https://user-images.githubusercontent.com/16078125/104949868-efb25700-59bf-11eb-841f-3adbad252cc2.png)
![org-step2](https://user-images.githubusercontent.com/16078125/105013534-a6095100-5a3f-11eb-923d-013896c59701.jpg) | ![org-step2](https://user-images.githubusercontent.com/16078125/104949875-f3de7480-59bf-11eb-9054-075bce75a75e.png)
![org-step3](https://user-images.githubusercontent.com/16078125/105013568-aefa2280-5a3f-11eb-89d4-81d623d4f938.jpg) | ![org-step3](https://user-images.githubusercontent.com/16078125/104949878-f5a83800-59bf-11eb-88c3-3585325003b9.png)

**Comment by clobber** [comment]
Looks nice except they are not High DPI.
